### ISSUE TITLE
Problem with uploading in product gallery in woocommerce

### ISSUE THREAD

**Issue by waqs0007** [zzxiang/external-media-without-import#10]
problem in uploading images in product gallery 
i add images in media from URL
image showing on product main image but not showing in product gallery 
KINDLY PLEASE SUGGEST ANY SOLUTION FOR UPLOADING IMAGES IN PRODUCT GALLERY FROM EXTERNAL SOURCES

**Comment by waqs0007** [comment]
Yes Sir its in WooCommerce when i adding products 
only working on product main image

but when i am adding photos in product gallery it successful shows when i click publish / update product it photos disappear
i will send screenshot

**Comment by zzxiang** [comment]
Just spent some time trying to install and learn to use WooCommerce. Do you mean "product gallery" by the part marked in red frame in the following screenshot?

![woocommerce product gallery](https://user-images.githubusercontent.com/10098144/46617933-120a6880-cb59-11e8-8d67-07e7d4fd2809.jpeg)

**Comment by waqs0007** [comment]
Yes Sir exactly i am asking about this product gallery
when i upload a photo from external source after update a product it dont show any photos

**Comment by waqs0007** [comment]
Dear any update on this issue ??

**Comment by zzxiang** [comment]
I'm very sorry that during the month I wasn't able to take time to improve this spare time project. :(

**Comment by zzxiang** [comment]
Sorry to keep you waiting. I've just released version 1.1.2 to fix this issue.
