### ISSUE TITLE
Plugin doesn't show after installation

### ISSUE THREAD

**Issue by jrameriz** [zzxiang/external-media-without-import#22]
after clicking on button the plugin shows a blank screen. 

![Screen Shot 2020-05-05 at 6 51 06 AM](https://user-images.githubusercontent.com/4984630/81073964-39dcc200-8e9d-11ea-823d-84383100d171.png)

**Comment by zzxiang** [comment]
What's your WordPress version? Seems that you are not using the latest version.

**Comment by jrameriz** [comment]
For the record tried 5.4.1 and didn't work. wondering if something is preventing it from showing. I tried it in a clean wordpress installed same version and it worked perfectly. Not sure what's going on.
