### ISSUE TITLE
[Feature Request] Bulk Import

### ISSUE THREAD

**Issue by traxim** [zzxiang/external-media-without-import#5]
First thank you for the Plugin. I have many images and it takes to long one by one. Can u add a function with more than one Link?

**Comment by zzxiang** [comment]
Thanks for the advice. Actually several users have sent me the feedback for this requirement. I'm considering on it.

**Comment by traxim** [comment]
Thx mate :)

**Comment by boogiedoll** [comment]
I need bulk import feature too. Will you add this feature soon? I can offer some development cost.

**Comment by zzxiang** [comment]
Thanks boogiedoll. Sorry that I just started new my life abroad and didn't quite have time on this plugin. Recently I finally have some time for it and I'm planning the feature these two months. Also very grateful that you are willing to offer some development cost. But at least for now I'm not going to SELL the plugin. I'm more willing to offer it as a free software. Maybe in future I'll set up a donation channel and if you are willing to donate to this plugin I'll be very happy :-)

**Comment by zzxiang** [comment]
Sorry, it's been really so late. I finally have some time to implement the bulk feature in [release 1.1](https://github.com/zzxiang/external-media-without-import/releases/tag/v1.1). Now multiple URL links can be added in batch to the media library, with one URL per line in the text box.
