### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by Vesa49** [zzxiang/external-media-without-import#7]
I run WP 4.9.4–fi and cannot activate plugin.
Is there way to fix it without coding skills?
"Parse error: syntax error, unexpected T_STRING in .......external-media-without-import.php on line 25"
Thanks Vesa

**Comment by zzxiang** [comment]
Seems it has something to do with localization. That's strange because I also use WP 4.9.4. But I don't know what's the difference between 4.9.4 and 4.9.4-fi. I'll first find out where's T_STRING is defined. Also, what's your PHP version?

**Comment by Vesa49** [comment]
Hi.
Apache Version 2.2.29
PHP Version 5.6.30
MySQL Version 5.5.51-38.2
Architecture x86_64
Operating System linux
I try to chance to php 7.
My isp is arvixe
The main need is to have media files outside wp root in common directory.
Havent find that jet. Your plugin was one option to try.
Thanks.

Vesa Löfström
Nokkamaantie 64
38670 Kalliala
+358445577222

2018-03-02 2:40 GMT+02:00 zzxiang <notifications@github.com>:

**Comment by zzxiang** [comment]
I did some investigation just now. Line 25 of external-media-without-import.php is just a namespace declaration. The parse error usually occurs on PHP version < 5.3 (see [PHP 5.3.0 Release Announcement](http://php.net/releases/5_3_0.php)). If you are using PHP version 5.6.30 it should be fine. Is it possible that there're multiple PHP versions installed on your server and your WordPress is using a version older than 5.3.0?

**Comment by Vesa49** [comment]
Softaculous info shows php 5.6.30. I dont know what wp is using,
With plugin Display PHP Vesion it shows  Running PHP version: *5.2.17*
Broblem solved.
Thanks.


Vesa Löfström
Nokkamaantie 64
38670 Kalliala
+358445577222

2018-03-04 11:49 GMT+02:00 zzxiang <notifications@github.com>:
